# 端口
server:
  port: 8001

# spring
spring:
  application:
    name: trade-shoes-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.118.202:8848

management:
  endpoints:
    web:
      exposure:
        include: '*'
