# 端口
server:
  port: 8003

# spring
spring:
  application:
    name: trade-shoes-capital
  cloud:
    nacos:
      discovery:
        server-addr: 47.98.118.202:8848
  datasource:
    url: jdbc:mysql://47.114.153.175:3306/capital?useSSL=false&allowMultiQueries=true
    username: root
    password: wx123456
    driver-class-name: com.mysql.cj.jdbc.Driver

management:
  endpoints:
    web:
      exposure:
        include: '*'

